name: ASU CIC CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest black flake8 coverage

      - name: Lint with black
        run: black --check .

      - name: Lint with flake8
        run: |
          if [ -d "src" ]; then flake8 src/; fi
          if [ -d "tests" ]; then flake8 tests/; fi

      - name: Run tests with coverage
        run: |
          coverage run -m pytest
          coverage report
